# Ingress
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-{{ project }}
  labels:
    app: {{ project }}
spec:
  rules:
    - host: HOST
      http:
        paths:
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: pwd-gen-svc
                port:
                  number: 8000
  tls:
    - hosts:
        - HOST
